# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				panda = true
				bee = true
				axolotl = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				allay = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				hoglin = true
				rabbit = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				vex = true
				wither_skeleton = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				minecart = true
				mooshroom = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				creeper = true
				lightning_bolt = true
				enderman = true
				chicken = true
				donkey = true
				tropical_fish = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				zombified_piglin = true
				piglin = true
				cat = true
				zombie = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				potion = true
				wolf = true
				villager = true
				skeleton_horse = true
				zombie_villager = true
				boat = true
				strider = true
				painting = true
				cave_spider = true
				cod = true
				witch = true
				spider = true

			[light_sources.settings.entities.graveyard]
				acolyte = true
				corrupted_vindicator = true
				skeleton_creeper = true
				corrupted_pillager = true
				ghoul = true
				nightmare = true

			[light_sources.settings.entities.betternether]
				naga_projectile = true
				firefly = true
				flying_pig = true
				hydrogen_jellyfish = true
				jungle_skeleton = true
				skull = true
				naga = true

			[light_sources.settings.entities.regions_unexplored]
				boat = true

			[light_sources.settings.entities.frycmobvariants]
				infected_piglin_brute = true
				tropical_spider = true
				corsair = true
				infected_piglin = true
				armored_spider = true
				forgotten = true
				cave_creeper = true
				explorer = true
				nightmare = true
				undead_warrior = true

			[light_sources.settings.entities.varietyaquatic]
				cuttlefish = true
				lionfish = true
				hermitcrab = true
				jellyfish = true
				yellowfin = true
				opah = true
				clownfish = true
				crab = true

			[light_sources.settings.entities.mutantmonsters]
				mutant_enderman = true
				mutant_creeper = true
				mutant_zombie = true
				mutant_skeleton = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

